### ISSUE TITLE
Accessing inherited component

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/LightningTestingService#18]
I'm testing a component that manages a date input field, which extends a base input component that handles the common aspects of an input, so label, error display etc. My initial test was simply to verify that the label I'd passed the component on creation was being applied correctly. 

The label is a regular HTML <label/> element, with an aura:id to make it accessible from the component, and is present in the base component. 

I've followed the approach in the examples and dynamically created the date component, but when I try to verify the label, component.find() always returns null. If I move the label into the date component, the find() works correctly and retrieves the label.

Initially I thought this might be down to the locker service (although I'd expect to be able to access everything in my namespace), but having downgraded all components to API 39 I still see the same behaviour. 

Is there something around the way that components are created for testing that isolates them from even the base components that they extend?

**Comment by esalman-sfdc** [comment]
There should not be anything special w.r.t testing which would cause this. 

Based on the description,  my understanding is that c:myDateInput component inherits behavior via extends="c:myInput". Is that correct?

I believe this is just how cmp.find() works. That is, it won't return you components from parent's body unless you explicitly do a find on parent via  cmp.getSuper().find(). 

LockerService would only come into play if super component is from a different namespace because in that case you won't be allowed to peak into its implementation details.

Feel free to share code snippet for more in depth conversation if this doesn't resolve the problem :)

**Comment by keirbowden** [comment]
Thanks for the response. You are correct about the inheritance. I'll try the method suggested and let you know how I get on tomorrow.

**Comment by keirbowden** [comment]
That did the trick. For some reason I thought components could find others on the same page in the same namespace. Clearly not.
