### ISSUE TITLE
Testing a method not exposed through component's public interface

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/LightningTestingService#22]
Is there a way to test a method that is not exposed through the component's public interface ? We may have some methods that need to be tested, but that we don't want to expose. 

In [exempleTests](https://github.com/forcedotcom/LightningTestingService/blob/master/lightning-component-tests/test/default/staticresources/exampleTests.resource) it seems that all methods are called via an `aura:method` in the related component.

**Comment by esalman-sfdc** [comment]
There are a couple of approaches that you could take,
- Expand component's interface via aura:method or event handlers to make it easier for the tests to invoke logic. Third party access can still be controlled via [access checks](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/access_components.htm). This pattern is similar to declaring methods as package-private while unit testing java.

- Extract reusable code out of components into javascript libs/modules. Utility methods (e.g. a sorting algorithm) can then be tested in isolation and pulled in as needed by lightning components. This [blog post](https://developer.salesforce.com/blogs/developer-relations/2016/12/lightning-components-code-sharing.html) talks about this in more detail.

Restrictions around what can be accessed/invoked are controlled by the platform (access checks, locker-service etc.) and apply to component tests as well. Based on personal experience, I think this does makes sense from test-quality perspective as it avoids issues going uncaught due to difference in behavior based on context/mode.

**Comment by FabienTaillon** [comment]
Ok, thanks !
