### ISSUE TITLE
Executing force:lightning:test:run from Docker container results in Unknown Error (13)

### ISSUE THREAD

**Issue by dancinllama** [forcedotcom/LightningTestingService#32]
I'm currently getting bitbucket pipelines set up and running in a CD environment, and using LightningTestService to run lightning component tests.  Bitbucket pipelines runs in a docker container. 

My script fails at the following:

sfdx force:lightning:test:run -a jasmineTests.app
Waiting to resolve the Lightning Experience-enabled custom domain........
ERROR running force:lightning:test:run:  An error occurred when running Lightning tests. An unknown server-side error occurred while processing the command. (UnknownError:13)

I'm using the default jasmineTests.app that comes with the "LTSExamples" package, and when I issue that same command from my local machine, it works fine.

Is it possible that since the script requires a browser to open, that this won't work from a "headless flow" or container?

**Comment by esalman-sfdc** [comment]
I am guessing that such an error could either be due to domain resolution issues (e.g. network firewalls/proxies) or due to web-driver config issues (e.g. inability to launch a browser properly 
 in an environment) which seems more likely based on the error message.

One of the community members had [reported](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1SAG&fId=0D53A00003BCg1kSAD) similar (not same) error on Travis but they were able to get around it by copying relevant pieces from .travis.yml file of the repo,

```
export DISPLAY=:99.0
sh -e /etc/init.d/xvfb start
sleep 3 # give xvfb some time to start
```
Wondering if you need something similar given this repo uses Travis/CircleCI environments to showcase CI flow and those are headless environments as well :)

**Comment by esalman-sfdc** [comment]
Cross Posting (for future visitors): 
Possible answer for this question shared [here](https://github.com/forcedotcom/LightningTestingService/issues/38#issuecomment-345542333) by another user.
